### ISSUE TITLE
Support for excluding columns

### ISSUE THREAD

**Issue by mattrobenolt** [mattrobenolt/pgtobq#6]
Being able to pass `-X password -X sensitive` for column names to filter out of syncing.

**Comment by sksembhi** [comment]
Hello, wanted to know if this is happening?

**Comment by mattrobenolt** [comment]
Maybe.

**Comment by sksembhi** [comment]
Damn.

**Comment by sksembhi** [comment]
Hello, following up

**Comment by mattrobenolt** [comment]
Pull requests accepted, this is extremely nontrivial.

**Comment by sksembhi** [comment]
wowowowowowowoaaa
